version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: cat packages/*/package.json | shasum > .dependencies_checksum
      - restore_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}
          paths:
            - node_modules

  run-tests:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: cat packages/*/package.json | shasum > .dependencies_checksum
      - restore_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}
      - run: yarn # symlink packages' node_modules
      - run: yarn build
      - run:
          name: "Run ganache"
          command: yarn ganache:ci
          background: true
      - run: cd packages/contracts/ && yarn migrate --network ganache
      - run: yarn test

  run-tslint:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: cat packages/*/package.json | shasum > .dependencies_checksum
      - restore_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}
      - run: yarn lint

workflows:
  version: 2
  run-tests:
    jobs:
      - build
      - run-tslint:
          requires:
            - build
      - run-tests:
          requires:
            - build
